# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 18:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0035_aperturatipogeneral_id_subtipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablasaperturas',
            name='oficina',
        ),
        migrations.RemoveField(
            model_name='tablasaperturas',
            name='sector',
        ),
        migrations.RemoveField(
            model_name='tablasaperturas',
            name='subtipo',
        ),
        migrations.RemoveField(
            model_name='tablasaperturas',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='tablasaperturas',
            name='zona',
        ),
        migrations.DeleteModel(
            name='TablasAperturas',
        ),
    ]
