# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 19:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0032_cadena'),
        ('panel', '0039_auto_20160201_1605'),
    ]

    operations = [
        migrations.CreateModel(
            name='TablasAperturas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel2', models.CharField(max_length=50)),
                ('mes', models.IntegerField()),
                ('year', models.IntegerField()),
                ('cadena_desc', models.CharField(max_length=50)),
                ('cod_material', models.CharField(max_length=50)),
                ('material', models.CharField(max_length=150)),
                ('kilos', models.FloatField()),
                ('netos', models.FloatField()),
                ('kilos_proy', models.FloatField()),
                ('neto_esperado', models.FloatField()),
                ('precio_fact', models.FloatField()),
                ('precio_lista', models.FloatField()),
                ('diferencia', models.FloatField()),
                ('cadena', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='maestros.Cadena')),
                ('oficina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maestros.OficinaVenta')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maestros.Sector')),
                ('subtipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maestros.SubtipoCliente')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maestros.TipoCliente')),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maestros.ZonaVenta')),
            ],
        ),
    ]
