# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-02 11:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0040_tablasaperturas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sectorgeneral',
            old_name='cumplimiento',
            new_name='cumpl_kilos',
        ),
    ]
