# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-02 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0041_auto_20160202_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectorgeneral',
            name='cumpl_netos',
            field=models.FloatField(default=0, null=True),
        ),
    ]
