# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-02 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0043_auto_20160202_0901'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cumplpptotipoclientegeneral',
            old_name='cumplimiento',
            new_name='cumpl_kilos',
        ),
        migrations.RenameField(
            model_name='cumplpptozonageneral',
            old_name='cumplimiento',
            new_name='cumpl_kilos',
        ),
        migrations.RenameField(
            model_name='tipogeneral',
            old_name='cumplimiento',
            new_name='cumpl_kilos',
        ),
        migrations.RenameField(
            model_name='zonageneral',
            old_name='cumplimiento',
            new_name='cumpl_kilos',
        ),
        migrations.AddField(
            model_name='cumplpptotipoclientegeneral',
            name='cumpl_netos',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='cumplpptozonageneral',
            name='cumpl_netos',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='tipogeneral',
            name='cumpl_netos',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='zonageneral',
            name='cumpl_netos',
            field=models.FloatField(default=0, null=True),
        ),
    ]
