# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-15 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0046_auto_20160215_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='tendenciasectorgeneral',
            name='mes',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='tendenciasectorgeneral',
            name='year',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='tendenciatipogeneral',
            name='mes',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='tendenciatipogeneral',
            name='year',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='tendenciazonageneral',
            name='mes',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='tendenciazonageneral',
            name='year',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
