# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-15 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0048_auto_20160215_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tendenciageneral',
            name='fecha',
            field=models.CharField(max_length=20),
        ),
    ]
