# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-16 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0049_auto_20160215_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='totalgeneral',
            name='kilos_proy',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='totalgeneral',
            name='netos_proy',
            field=models.FloatField(default=0, null=True),
        ),
    ]
