# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0031_nivel2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cadena',
            fields=[
                ('codigo', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('cadena', models.CharField(max_length=50)),
            ],
        ),
    ]
