# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-12 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0032_cadena'),
    ]

    operations = [
        migrations.CreateModel(
            name='KONP_Paso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registro', models.CharField(max_length=50)),
                ('importe', models.FloatField(default=0)),
                ('um', models.CharField(max_length=10)),
            ],
        ),
    ]
